### ISSUE TITLE
maximum recursion depth exceeded in `width_aware_slice`

### ISSUE THREAD

**Issue by sshilovsky** [thomasballinger/curtsies#88]
1.

    >>> FmtStr(u'').width_aware_slice(0)
    RuntimeError: maximum recursion depth exceeded
expected:
    
    IndexError
2.

    >>> FmtStr(u'').width_aware_slice(slice(0, 100, None))
    RuntimeError: maximum recursion depth exceeded
expected:

    FmtStr(u'')

curtsies 0.2.6, python 2.7

**Comment by thomasballinger** [comment]
Hm that's sure not great.

This is because FmtStr's constructor doesn't take unicode strings, and should not be directly constructed. Instead, use 

    >>> from curtsies.formatstring import fmtstr
    >>> f = fmtstr(u'asdf')
    >>> f.width_aware_slice(2)
    'd'

However this is very confusing. I'll look at doing a typecheck in the constructor, and at least adding a docstring. There are some typechecks currently in the code that have been commented out because they were killing performance.

If I designed this again I would absolutely use a classmethod for this instead and use something like fmtstr for the constructor.

**Comment by thomasballinger** [comment]
Closed because I'm not changing the (poor) api anytime soon.
